development:
  adapter: postgresql
  database: bds_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: bds_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bds_production
  pool: 5
  timeout: 5000
